# Generated by Django 4.2.2 on 2024-11-20 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_farmer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Farmer",
        ),
    ]
