# Generated by Django 4.2.2 on 2024-11-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
