# Generated by Django 4.2.2 on 2024-11-30 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_deliveryoption_order_delivery_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_option",
        ),
        migrations.DeleteModel(
            name="DeliveryOption",
        ),
    ]
