# Generated by Django 4.2.2 on 2024-11-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
