# Generated by Django 4.2.2 on 2024-11-19 08:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_farmer_is_approved"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_profile",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="popularity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
