# Generated by Django 4.2.2 on 2024-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productimage_product_low_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pid",
            field=models.CharField(
                editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
