# Generated by Django 4.2.2 on 2024-11-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pid",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
