# Generated by Django 4.2.2 on 2024-11-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_pid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, to="products.productimage"),
        ),
    ]
