# Generated by Django 4.2.2 on 2024-11-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_farmer_is_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/image.png", upload_to="profile_pictures/"
            ),
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.TextField()),
                ("resources", models.JSONField(blank=True, null=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm",
                        to="products.farmer",
                    ),
                ),
            ],
        ),
    ]
